server:
  port: 8081
  tomcat:
    max-connections: 100000           # 设置最大连接数
    max-threads: 5000                # 设置最大线程数
    connection-timeout: 20000        # 设置连接超时时间（单位：毫秒）
    keep-alive-timeout: 60000        # 设置保持连接的最大时间（单位：毫秒）
